#define IDENT                            1
#define UIDENT                           2
#define FCONST                           3
#define SCONST                           4
#define USCONST                          5
#define BCONST                           6
#define XCONST                           7
#define OP                               8
#define ICONST                           9
#define PARAM                           10
#define TYPECAST                        11
#define DOT_DOT                         12
#define COLON_EQUALS                    13
#define EQUALS_GREATER                  14
#define LESS_EQUALS                     15
#define GREATER_EQUALS                  16
#define NOT_EQUALS                      17
#define RIGHT_ARROW                     18
#define ABORT_P                         19
#define ABSENT                          20
#define ABSOLUTE_P                      21
#define ACCESS                          22
#define ACTION                          23
#define ADD_P                           24
#define ADMIN                           25
#define AFTER                           26
#define AGGREGATE                       27
#define ALL                             28
#define ALSO                            29
#define ALTER                           30
#define ALWAYS                          31
#define ANALYSE                         32
#define ANALYZE                         33
#define AND                             34
#define ANY                             35
#define ARRAY                           36
#define AS                              37
#define ASC                             38
#define ASENSITIVE                      39
#define ASSERTION                       40
#define ASSIGNMENT                      41
#define ASYMMETRIC                      42
#define AT                              43
#define ATOMIC                          44
#define ATTACH                          45
#define ATTRIBUTE                       46
#define AUTHORIZATION                   47
#define BACKWARD                        48
#define BEFORE                          49
#define BEGIN_P                         50
#define BETWEEN                         51
#define BIGINT                          52
#define BINARY                          53
#define BIT                             54
#define BOOLEAN_P                       55
#define BOTH                            56
#define BREADTH                         57
#define BY                              58
#define CACHE                           59
#define CALL                            60
#define CALLED                          61
#define CASCADE                         62
#define CASCADED                        63
#define CASE                            64
#define CAST                            65
#define CATALOG_P                       66
#define CHAIN                           67
#define CHAR_P                          68
#define CHARACTER                       69
#define CHARACTERISTICS                 70
#define CHECK                           71
#define CHECKPOINT                      72
#define CLASS                           73
#define CLOSE                           74
#define CLUSTER                         75
#define COALESCE                        76
#define COLLATE                         77
#define COLLATION                       78
#define COLUMN                          79
#define COLUMNS                         80
#define COMMENT                         81
#define COMMENTS                        82
#define COMMIT                          83
#define COMMITTED                       84
#define COMPRESSION                     85
#define CONCURRENTLY                    86
#define CONDITIONAL                     87
#define CONFIGURATION                   88
#define CONFLICT                        89
#define CONNECTION                      90
#define CONSTRAINT                      91
#define CONSTRAINTS                     92
#define CONTENT_P                       93
#define CONTINUE_P                      94
#define CONVERSION_P                    95
#define COPY                            96
#define COST                            97
#define CREATE                          98
#define CROSS                           99
#define CSV                            100
#define CUBE                           101
#define CURRENT_P                      102
#define CURRENT_CATALOG                103
#define CURRENT_DATE                   104
#define CURRENT_ROLE                   105
#define CURRENT_SCHEMA                 106
#define CURRENT_TIME                   107
#define CURRENT_TIMESTAMP              108
#define CURRENT_USER                   109
#define CURSOR                         110
#define CYCLE                          111
#define DATA_P                         112
#define DATABASE                       113
#define DAY_P                          114
#define DEALLOCATE                     115
#define DEC                            116
#define DECIMAL_P                      117
#define DECLARE                        118
#define DEFAULT                        119
#define DEFAULTS                       120
#define DEFERRABLE                     121
#define DEFERRED                       122
#define DEFINER                        123
#define DELETE_P                       124
#define DELIMITER                      125
#define DELIMITERS                     126
#define DEPENDS                        127
#define DEPTH                          128
#define DESC                           129
#define DESTINATION                    130
#define DETACH                         131
#define DICTIONARY                     132
#define DISABLE_P                      133
#define DISCARD                        134
#define DISTINCT                       135
#define DO                             136
#define DOCUMENT_P                     137
#define DOMAIN_P                       138
#define DOUBLE_P                       139
#define DROP                           140
#define EACH                           141
#define EDGE                           142
#define ELSE                           143
#define EMPTY_P                        144
#define ENABLE_P                       145
#define ENCODING                       146
#define ENCRYPTED                      147
#define END_P                          148
#define ENFORCED                       149
#define ENUM_P                         150
#define ERROR_P                        151
#define ESCAPE                         152
#define EVENT                          153
#define EXCEPT                         154
#define EXCLUDE                        155
#define EXCLUDING                      156
#define EXCLUSIVE                      157
#define EXECUTE                        158
#define EXISTS                         159
#define EXPLAIN                        160
#define EXPRESSION                     161
#define EXTENSION                      162
#define EXTERNAL                       163
#define EXTRACT                        164
#define FALSE_P                        165
#define FAMILY                         166
#define FETCH                          167
#define FILTER                         168
#define FINALIZE                       169
#define FIRST_P                        170
#define FLOAT_P                        171
#define FOLLOWING                      172
#define FOR                            173
#define FORCE                          174
#define FOREIGN                        175
#define FORMAT                         176
#define FORWARD                        177
#define FREEZE                         178
#define FROM                           179
#define FULL                           180
#define FUNCTION                       181
#define FUNCTIONS                      182
#define GENERATED                      183
#define GLOBAL                         184
#define GRANT                          185
#define GRANTED                        186
#define GRAPH                          187
#define GRAPH_TABLE                    188
#define GREATEST                       189
#define GROUP_P                        190
#define GROUPING                       191
#define GROUPS                         192
#define HANDLER                        193
#define HAVING                         194
#define HEADER_P                       195
#define HOLD                           196
#define HOUR_P                         197
#define IDENTITY_P                     198
#define IF_P                           199
#define IGNORE_P                       200
#define ILIKE                          201
#define IMMEDIATE                      202
#define IMMUTABLE                      203
#define IMPLICIT_P                     204
#define IMPORT_P                       205
#define IN_P                           206
#define INCLUDE                        207
#define INCLUDING                      208
#define INCREMENT                      209
#define INDENT                         210
#define INDEX                          211
#define INDEXES                        212
#define INHERIT                        213
#define INHERITS                       214
#define INITIALLY                      215
#define INLINE_P                       216
#define INNER_P                        217
#define INOUT                          218
#define INPUT_P                        219
#define INSENSITIVE                    220
#define INSERT                         221
#define INSTEAD                        222
#define INT_P                          223
#define INTEGER                        224
#define INTERSECT                      225
#define INTERVAL                       226
#define INTO                           227
#define INVOKER                        228
#define IS                             229
#define ISNULL                         230
#define ISOLATION                      231
#define JOIN                           232
#define JSON                           233
#define JSON_ARRAY                     234
#define JSON_ARRAYAGG                  235
#define JSON_EXISTS                    236
#define JSON_OBJECT                    237
#define JSON_OBJECTAGG                 238
#define JSON_QUERY                     239
#define JSON_SCALAR                    240
#define JSON_SERIALIZE                 241
#define JSON_TABLE                     242
#define JSON_VALUE                     243
#define KEEP                           244
#define KEY                            245
#define KEYS                           246
#define LABEL                          247
#define LANGUAGE                       248
#define LARGE_P                        249
#define LAST_P                         250
#define LATERAL_P                      251
#define LEADING                        252
#define LEAKPROOF                      253
#define LEAST                          254
#define LEFT                           255
#define LEVEL                          256
#define LIKE                           257
#define LIMIT                          258
#define LISTEN                         259
#define LOAD                           260
#define LOCAL                          261
#define LOCALTIME                      262
#define LOCALTIMESTAMP                 263
#define LOCATION                       264
#define LOCK_P                         265
#define LOCKED                         266
#define LOGGED                         267
#define LSN_P                          268
#define MAPPING                        269
#define MATCH                          270
#define MATCHED                        271
#define MATERIALIZED                   272
#define MAXVALUE                       273
#define MERGE                          274
#define MERGE_ACTION                   275
#define METHOD                         276
#define MINUTE_P                       277
#define MINVALUE                       278
#define MODE                           279
#define MONTH_P                        280
#define MOVE                           281
#define NAME_P                         282
#define NAMES                          283
#define NATIONAL                       284
#define NATURAL                        285
#define NCHAR                          286
#define NESTED                         287
#define NEW                            288
#define NEXT                           289
#define NFC                            290
#define NFD                            291
#define NFKC                           292
#define NFKD                           293
#define NO                             294
#define NODE                           295
#define NONE                           296
#define NORMALIZE                      297
#define NORMALIZED                     298
#define NOT                            299
#define NOTHING                        300
#define NOTIFY                         301
#define NOTNULL                        302
#define NOWAIT                         303
#define NULL_P                         304
#define NULLIF                         305
#define NULLS_P                        306
#define NUMERIC                        307
#define OBJECT_P                       308
#define OBJECTS_P                      309
#define OF                             310
#define OFF                            311
#define OFFSET                         312
#define OIDS                           313
#define OLD                            314
#define OMIT                           315
#define ON                             316
#define ONLY                           317
#define OPERATOR                       318
#define OPTION                         319
#define OPTIONS                        320
#define OR                             321
#define ORDER                          322
#define ORDINALITY                     323
#define OTHERS                         324
#define OUT_P                          325
#define OUTER_P                        326
#define OVER                           327
#define OVERLAPS                       328
#define OVERLAY                        329
#define OVERRIDING                     330
#define OWNED                          331
#define OWNER                          332
#define PARALLEL                       333
#define PARAMETER                      334
#define PARSER                         335
#define PARTIAL                        336
#define PARTITION                      337
#define PARTITIONS                     338
#define PASSING                        339
#define PASSWORD                       340
#define PATH                           341
#define PERIOD                         342
#define PLACING                        343
#define PLAN                           344
#define PLANS                          345
#define POLICY                         346
#define POSITION                       347
#define PRECEDING                      348
#define PRECISION                      349
#define PREPARE                        350
#define PREPARED                       351
#define PRESERVE                       352
#define PRIMARY                        353
#define PRIOR                          354
#define PRIVILEGES                     355
#define PROCEDURAL                     356
#define PROCEDURE                      357
#define PROCEDURES                     358
#define PROGRAM                        359
#define PROPERTIES                     360
#define PROPERTY                       361
#define PUBLICATION                    362
#define QUOTE                          363
#define QUOTES                         364
#define RANGE                          365
#define READ                           366
#define REAL                           367
#define REASSIGN                       368
#define RECURSIVE                      369
#define REF_P                          370
#define REFERENCES                     371
#define REFERENCING                    372
#define REFRESH                        373
#define REINDEX                        374
#define RELATIONSHIP                   375
#define RELATIVE_P                     376
#define RELEASE                        377
#define RENAME                         378
#define REPACK                         379
#define REPEATABLE                     380
#define REPLACE                        381
#define REPLICA                        382
#define RESET                          383
#define RESPECT_P                      384
#define RESTART                        385
#define RESTRICT                       386
#define RETURN                         387
#define RETURNING                      388
#define RETURNS                        389
#define REVOKE                         390
#define RIGHT                          391
#define ROLE                           392
#define ROLLBACK                       393
#define ROLLUP                         394
#define ROUTINE                        395
#define ROUTINES                       396
#define ROW                            397
#define ROWS                           398
#define RULE                           399
#define SAVEPOINT                      400
#define SCALAR                         401
#define SCHEMA                         402
#define SCHEMAS                        403
#define SCROLL                         404
#define SEARCH                         405
#define SECOND_P                       406
#define SECURITY                       407
#define SELECT                         408
#define SEQUENCE                       409
#define SEQUENCES                      410
#define SERIALIZABLE                   411
#define SERVER                         412
#define SESSION                        413
#define SESSION_USER                   414
#define SET                            415
#define SETOF                          416
#define SETS                           417
#define SHARE                          418
#define SHOW                           419
#define SIMILAR                        420
#define SIMPLE                         421
#define SKIP                           422
#define SMALLINT                       423
#define SNAPSHOT                       424
#define SOME                           425
#define SOURCE                         426
#define SPLIT                          427
#define SQL_P                          428
#define STABLE                         429
#define STANDALONE_P                   430
#define START                          431
#define STATEMENT                      432
#define STATISTICS                     433
#define STDIN                          434
#define STDOUT                         435
#define STORAGE                        436
#define STORED                         437
#define STRICT_P                       438
#define STRING_P                       439
#define STRIP_P                        440
#define SUBSCRIPTION                   441
#define SUBSTRING                      442
#define SUPPORT                        443
#define SYMMETRIC                      444
#define SYSID                          445
#define SYSTEM_P                       446
#define SYSTEM_USER                    447
#define TABLE                          448
#define TABLES                         449
#define TABLESAMPLE                    450
#define TABLESPACE                     451
#define TARGET                         452
#define TEMP                           453
#define TEMPLATE                       454
#define TEMPORARY                      455
#define TEXT_P                         456
#define THEN                           457
#define TIES                           458
#define TIME                           459
#define TIMESTAMP                      460
#define TO                             461
#define TRAILING                       462
#define TRANSACTION                    463
#define TRANSFORM                      464
#define TREAT                          465
#define TRIGGER                        466
#define TRIM                           467
#define TRUE_P                         468
#define TRUNCATE                       469
#define TRUSTED                        470
#define TYPE_P                         471
#define TYPES_P                        472
#define UESCAPE                        473
#define UNBOUNDED                      474
#define UNCONDITIONAL                  475
#define UNCOMMITTED                    476
#define UNENCRYPTED                    477
#define UNION                          478
#define UNIQUE                         479
#define UNKNOWN                        480
#define UNLISTEN                       481
#define UNLOGGED                       482
#define UNTIL                          483
#define UPDATE                         484
#define USER                           485
#define USING                          486
#define VACUUM                         487
#define VALID                          488
#define VALIDATE                       489
#define VALIDATOR                      490
#define VALUE_P                        491
#define VALUES                         492
#define VARCHAR                        493
#define VARIADIC                       494
#define VARYING                        495
#define VERBOSE                        496
#define VERSION_P                      497
#define VERTEX                         498
#define VIEW                           499
#define VIEWS                          500
#define VIRTUAL                        501
#define VOLATILE                       502
#define WAIT                           503
#define WHEN                           504
#define WHERE                          505
#define WHITESPACE_P                   506
#define WINDOW                         507
#define WITH                           508
#define WITHIN                         509
#define WITHOUT                        510
#define WORK                           511
#define WRAPPER                        512
#define WRITE                          513
#define XML_P                          514
#define XMLATTRIBUTES                  515
#define XMLCONCAT                      516
#define XMLELEMENT                     517
#define XMLEXISTS                      518
#define XMLFOREST                      519
#define XMLNAMESPACES                  520
#define XMLPARSE                       521
#define XMLPI                          522
#define XMLROOT                        523
#define XMLSERIALIZE                   524
#define XMLTABLE                       525
#define YEAR_P                         526
#define YES_P                          527
#define ZONE                           528
#define FORMAT_LA                      529
#define NOT_LA                         530
#define NULLS_LA                       531
#define WITH_LA                        532
#define WITHOUT_LA                     533
#define MODE_TYPE_NAME                 534
#define MODE_PLPGSQL_EXPR              535
#define MODE_PLPGSQL_ASSIGN1           536
#define MODE_PLPGSQL_ASSIGN2           537
#define MODE_PLPGSQL_ASSIGN3           538
#define UMINUS                         539
#define LT                             540
#define GT                             541
#define EQ                             542
#define PIPE                           543
#define PLUS                           544
#define MINUS                          545
#define STAR                           546
#define SLASH                          547
#define PERCENT                        548
#define CARET                          549
#define LBRACKET                       550
#define RBRACKET                       551
#define LPAREN                         552
#define RPAREN                         553
#define DOT                            554
#define COMMA                          555
#define SEMICOLON                      556
#define COLON                          557
#define HASH                           558
#define LBRACE                         559
#define RBRACE                         560
