//! Raw FFI bindings to the Lime parser generator C library.
//!
//! This crate provides unsafe, low-level bindings generated by `bindgen`.
//! Higher-level safe wrappers belong in the `lime-rs` crate.

// Bindgen-generated code triggers these — suppress for FFI.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::unreadable_literal)]
#![allow(clippy::pub_underscore_fields)]
#![allow(clippy::unseparated_literal_suffix)]
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
