//! Rule registry mapping rule IDs to numeric indices.
//!
//! This module provides zero-overhead rule tracking using sparse bitmaps.
//! Rules are assigned compile-time numeric IDs, enabling efficient set
//! operations (union, intersection) without string comparisons.
//!
//! # Design
//!
//! - Each rule gets a unique `u16` ID (supports up to 65,536 rules)
//! - Tracking uses `SparseMap` (sparse bitmap) instead of `Vec<String>`
//! - Only enabled when `--rules` flag is passed (CLI) or `track_rules` is set (API)
//! - Zero overhead in production (PostgreSQL, Stoolap) when disabled

use sparsemap::SparseMap;
use std::sync::OnceLock;

/// Rule ID type (supports up to 65,536 rules).
pub type RuleId = u16;

/// Maximum number of rules supported.
pub const MAX_RULES: usize = 65536;

/// Set of applied rules, represented as a sparse bitmap.
#[derive(Debug, Clone)]
pub struct RuleSet {
    bitmap: SparseMap,
}

impl RuleSet {
    /// Create an empty rule set.
    #[must_use]
    pub fn new() -> Self {
        Self {
            bitmap: SparseMap::new(),
        }
    }

    /// Record that a rule was applied.
    #[inline]
    pub fn mark_applied(&mut self, rule_id: RuleId) {
        self.bitmap.set(rule_id as u32);
    }

    /// Check if a rule was applied.
    #[must_use]
    #[inline]
    pub fn was_applied(&self, rule_id: RuleId) -> bool {
        self.bitmap.is_set(rule_id as u32)
    }

    /// Count total rules applied.
    #[must_use]
    pub fn count(&self) -> u32 {
        self.bitmap.count()
    }

    /// Union with another rule set (self |= other).
    pub fn union(&mut self, other: &Self) {
        self.bitmap.union(&other.bitmap);
    }

    /// Intersect with another rule set (self &= other).
    pub fn intersect(&mut self, other: &Self) {
        self.bitmap.intersect(&other.bitmap);
    }

    /// Iterate over applied rule IDs.
    pub fn iter(&self) -> impl Iterator<Item = RuleId> + '_ {
        self.bitmap.iter().map(|id| id as RuleId)
    }

    /// Convert to a list of rule names for display.
    #[must_use]
    pub fn to_names(&self) -> Vec<String> {
        self.iter()
            .filter_map(|id| registry().id_to_name(id))
            .map(|s| s.to_owned())
            .collect()
    }
}

impl Default for RuleSet {
    fn default() -> Self {
        Self::new()
    }
}

/// Rule metadata.
#[derive(Debug, Clone)]
pub struct RuleInfo {
    pub id: RuleId,
    pub name: &'static str,
    pub category: &'static str,
}

/// Global rule registry (initialized at compile time).
pub struct RuleRegistry {
    rules: Vec<RuleInfo>,
}

impl RuleRegistry {
    const fn new() -> Self {
        Self { rules: Vec::new() }
    }

    fn init(&mut self) {
        // Register all rules with numeric IDs
        // This will be generated by a build script in the future
        self.register(0, "filter-pushdown", "logical");
        self.register(1, "join-commutativity", "logical");
        self.register(2, "join-associativity", "logical");
        self.register(3, "predicate-pushdown-through-join", "logical");
        self.register(4, "predicate-pushdown-through-aggregate", "logical");
        self.register(5, "column-pruning", "logical");
        self.register(6, "limit-pushdown", "logical");
        self.register(7, "join-elimination", "logical");
        self.register(8, "subquery-unnesting", "logical");
        self.register(9, "common-subexpression-elimination", "logical");
        self.register(10, "constant-folding", "logical");
        self.register(11, "predicate-simplification", "logical");
        self.register(12, "null-propagation", "logical");
        self.register(13, "outer-join-to-inner-join", "logical");
        self.register(14, "filter-merge", "logical");
        self.register(15, "project-merge", "logical");
        // ... more rules would be registered here
        // TODO: Generate this automatically from .rra files
    }

    fn register(&mut self, id: RuleId, name: &'static str, category: &'static str) {
        self.rules.push(RuleInfo {
            id,
            name,
            category,
        });
    }

    /// Get rule name by ID.
    #[must_use]
    pub fn id_to_name(&self, id: RuleId) -> Option<&'static str> {
        self.rules
            .iter()
            .find(|r| r.id == id)
            .map(|r| r.name)
    }

    /// Get rule ID by name.
    #[must_use]
    pub fn name_to_id(&self, name: &str) -> Option<RuleId> {
        self.rules
            .iter()
            .find(|r| r.name == name)
            .map(|r| r.id)
    }

    /// Get all registered rules.
    #[must_use]
    pub fn all_rules(&self) -> &[RuleInfo] {
        &self.rules
    }
}

/// Global rule registry instance.
static RULE_REGISTRY: OnceLock<RuleRegistry> = OnceLock::new();

/// Get the global rule registry.
#[must_use]
pub fn registry() -> &'static RuleRegistry {
    RULE_REGISTRY.get_or_init(|| {
        let mut reg = RuleRegistry::new();
        reg.init();
        reg
    })
}

/// Convenience macro to get a rule ID by name at compile time.
/// Falls back to runtime lookup if name is not a literal.
#[macro_export]
macro_rules! rule_id {
    ($name:literal) => {{
        // TODO: In the future, this could be a const lookup
        // For now, runtime lookup
        $crate::rule_registry::registry()
            .name_to_id($name)
            .expect(concat!("rule not found: ", $name))
    }};
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_rule_set_basic() {
        let mut set = RuleSet::new();
        assert_eq!(set.count(), 0);

        set.mark_applied(5);
        assert!(set.was_applied(5));
        assert!(!set.was_applied(6));
        assert_eq!(set.count(), 1);
    }

    #[test]
    fn test_rule_set_union() {
        let mut set1 = RuleSet::new();
        set1.mark_applied(1);
        set1.mark_applied(2);

        let mut set2 = RuleSet::new();
        set2.mark_applied(2);
        set2.mark_applied(3);

        set1.union(&set2);
        assert!(set1.was_applied(1));
        assert!(set1.was_applied(2));
        assert!(set1.was_applied(3));
        assert_eq!(set1.count(), 3);
    }

    #[test]
    fn test_rule_set_intersect() {
        let mut set1 = RuleSet::new();
        set1.mark_applied(1);
        set1.mark_applied(2);
        set1.mark_applied(3);

        let mut set2 = RuleSet::new();
        set2.mark_applied(2);
        set2.mark_applied(3);
        set2.mark_applied(4);

        set1.intersect(&set2);
        assert!(!set1.was_applied(1));
        assert!(set1.was_applied(2));
        assert!(set1.was_applied(3));
        assert!(!set1.was_applied(4));
        assert_eq!(set1.count(), 2);
    }

    #[test]
    fn test_registry_lookup() {
        let reg = registry();

        // Should have registered rules
        assert!(!reg.all_rules().is_empty());

        // Lookup by ID
        let name = reg.id_to_name(0);
        assert!(name.is_some());

        // Lookup by name
        if let Some(name) = name {
            let id = reg.name_to_id(name);
            assert_eq!(id, Some(0));
        }
    }
}
