//! PostgreSQL snapshot capture commands.
//!
//! Provides CLI commands for capturing fingerprint snapshots from live
//! PostgreSQL databases. These snapshots can be used with the timeline
//! system for deterministic testing and what-if analysis.

use std::path::Path;

use anyhow::{bail, Context, Result};
use colored::Colorize;

/// Capture a snapshot from a PostgreSQL database.
///
/// Connects to the database and queries system catalogs to capture:
/// - Schema information (tables, columns, indexes, constraints)
/// - Statistics (row counts, NDV, histograms, correlations)
/// - Hardware profile
/// - Database configuration
///
/// The snapshot is written to a TOML file that can be used with
/// the timeline system.
pub fn capture_pg_snapshot(
    _database_url: &str,
    _tables: &[String],
    output_path: &Path,
    label: Option<String>,
) -> Result<()> {
    eprintln!("{}", "Connecting to PostgreSQL...".cyan());

    // Note: This would require libpq bindings or a PostgreSQL client library.
    // For now, we provide a template implementation that could be filled in
    // with actual database connection logic.

    eprintln!(
        "{}",
        "WARNING: Direct PostgreSQL connection not yet implemented.".yellow()
    );
    eprintln!("{}", "Use the extension SQL functions instead:".yellow());
    eprintln!();
    eprintln!("  {}", "-- Load the extension".bright_black());
    eprintln!("  {}", "CREATE EXTENSION IF NOT EXISTS pg_ra_planner;");
    eprintln!();
    eprintln!("  {}", "-- Capture snapshot".bright_black());
    eprintln!("  {}", "SELECT ra.capture_snapshot_to_file(");
    eprintln!("    {}", "ARRAY['public.orders', 'public.customers'],");
    eprintln!("    {},", format!("'{}'", output_path.display()));
    if let Some(ref lbl) = label {
        eprintln!("    {}", format!("'{lbl}'"));
    } else {
        eprintln!("    {}", "NULL");
    }
    eprintln!("  {}", ");");
    eprintln!();

    bail!("Direct PostgreSQL connection not implemented - use extension SQL functions")
}

/// Generate SQL script to capture snapshots.
///
/// Creates a SQL script that can be executed in psql to capture
/// timeline snapshots at specified intervals.
pub fn generate_capture_script(
    tables: &[String],
    output_dir: &Path,
    interval_seconds: Option<u64>,
) -> Result<String> {
    let mut script = String::new();

    script.push_str("-- PostgreSQL snapshot capture script\n");
    script.push_str("-- Generated by ra-cli\n");
    script.push_str("--\n");
    script.push_str("-- Usage: psql -d DATABASE -f script.sql\n\n");

    script.push_str("-- Load extension\n");
    script.push_str("CREATE EXTENSION IF NOT EXISTS pg_ra_planner;\n\n");

    // Format table list
    let table_array = format!(
        "ARRAY[{}]",
        tables
            .iter()
            .map(|t| format!("'{t}'"))
            .collect::<Vec<_>>()
            .join(", ")
    );

    if let Some(interval) = interval_seconds {
        script.push_str("-- Capture initial snapshot\n");
        script.push_str(&format!(
            "SELECT ra.capture_snapshot_to_file(\n  {},\n  '{}',\n  'Initial snapshot'\n);\n\n",
            table_array,
            output_dir.join("snapshot_0.toml").display()
        ));

        script.push_str(&format!("-- Wait {interval} seconds\n"));
        script.push_str(&format!("SELECT pg_sleep({interval});\n\n"));

        script.push_str("-- Capture subsequent snapshot\n");
        script.push_str(&format!(
            "SELECT ra.capture_snapshot_to_file(\n  {},\n  '{}',\n  'After {} seconds'\n);\n",
            table_array,
            output_dir
                .join(format!("snapshot_{interval}.toml"))
                .display(),
            interval
        ));
    } else {
        script.push_str("-- Capture snapshot\n");
        script.push_str(&format!(
            "SELECT ra.capture_snapshot_to_file(\n  {},\n  '{}',\n  'Snapshot'\n);\n",
            table_array,
            output_dir.join("snapshot.toml").display()
        ));
    }

    Ok(script)
}

/// Merge multiple snapshots into a timeline configuration.
///
/// Takes a directory of snapshot TOML files and combines them into
/// a single timeline configuration with proper time offsets and metadata.
pub fn merge_snapshots_to_timeline(
    snapshot_dir: &Path,
    output_path: &Path,
    timeline_name: &str,
    timeline_description: &str,
) -> Result<()> {
    use ra_engine::timeline_config::{
        FingerPrintSnapshot, HardwareProfileDef, TimelineConfig, TimelineMetadata,
    };
    use std::collections::BTreeMap;

    eprintln!("{}", "Scanning snapshot directory...".cyan());

    // Find all snapshot TOML files
    let mut snapshots = BTreeMap::new();
    for entry in std::fs::read_dir(snapshot_dir).context("Failed to read snapshot directory")? {
        let entry = entry?;
        let path = entry.path();

        if path.extension().and_then(|s| s.to_str()) != Some("toml") {
            continue;
        }

        // Parse snapshot filename to extract time offset
        let file_stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default();

        // Look for pattern: snapshot_N.toml where N is time offset
        let time_offset = if let Some(offset_str) = file_stem.strip_prefix("snapshot_") {
            offset_str.parse::<u64>().unwrap_or(0)
        } else {
            0
        };

        // Read and parse snapshot
        let content = std::fs::read_to_string(&path)
            .with_context(|| format!("Failed to read {}", path.display()))?;

        let snapshot: FingerPrintSnapshot = toml::from_str(&content)
            .with_context(|| format!("Failed to parse {}", path.display()))?;

        snapshots.insert(time_offset, snapshot);
    }

    if snapshots.is_empty() {
        bail!("No snapshot files found in {}", snapshot_dir.display());
    }

    eprintln!(
        "{}",
        format!("Found {} snapshot(s)", snapshots.len()).green()
    );

    // Extract unique hardware profiles
    let mut hardware_profiles = Vec::new();
    let mut seen_profiles = std::collections::HashSet::new();

    for snapshot in snapshots.values() {
        if seen_profiles.insert(&snapshot.hardware_profile) {
            // Create a hardware profile definition
            // Note: We'd need to extract this from the snapshot or use defaults
            hardware_profiles.push(HardwareProfileDef {
                name: snapshot.hardware_profile.clone(),
                cpu_cores: 4,
                total_memory: 16_000_000_000,
                available_memory: Some(12_000_000_000),
                simd_width: 256,
                has_gpu: false,
                gpu_memory: None,
                l1_cache_size: 32768,
                l2_cache_size: 262144,
                l3_cache_size: 8388608,
            });
        }
    }

    // Build timeline configuration
    let timeline = TimelineConfig {
        metadata: TimelineMetadata {
            name: timeline_name.to_string(),
            description: timeline_description.to_string(),
            query: None,
            dialect: Some("postgresql".to_string()),
            duration_seconds: snapshots.keys().last().copied(),
            schema: None,
            scale_factor: None,
        },
        hardware_profiles,
        snapshots: snapshots.into_values().collect(),
        events: Vec::new(),
        expectations: Vec::new(),
    };

    // Validate timeline
    timeline
        .validate()
        .context("Generated timeline failed validation")?;

    // Write to file
    let toml_str = toml::to_string_pretty(&timeline).context("Failed to serialize timeline")?;

    std::fs::write(output_path, toml_str)
        .with_context(|| format!("Failed to write {}", output_path.display()))?;

    eprintln!(
        "{}",
        format!("Timeline written to {}", output_path.display()).green()
    );
    eprintln!("  {} snapshots", timeline.snapshot_count());
    eprintln!("  {} hardware profiles", timeline.hardware_profiles.len());
    eprintln!("  {} tables", timeline.table_names().len());

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_script_single_snapshot() {
        let tables = vec!["public.orders".to_string(), "public.customers".to_string()];
        let output_dir = Path::new("/tmp");

        let script = generate_capture_script(&tables, output_dir, None).unwrap();

        assert!(script.contains("CREATE EXTENSION"));
        assert!(script.contains("ra.capture_snapshot_to_file"));
        assert!(script.contains("public.orders"));
        assert!(script.contains("public.customers"));
    }

    #[test]
    fn generate_script_with_interval() {
        let tables = vec!["public.orders".to_string()];
        let output_dir = Path::new("/tmp");

        let script = generate_capture_script(&tables, output_dir, Some(3600)).unwrap();

        assert!(script.contains("pg_sleep(3600)"));
        assert!(script.contains("snapshot_0.toml"));
        assert!(script.contains("snapshot_3600.toml"));
    }
}
