//! `PGS_*` strategy-mask bits.
//!
//! Bit values are pinned to `PostgreSQL`'s `pathnodes.h:66-86`
//! layout so that advice generated by Ra can be honored by PG and
//! vice versa. Do not renumber.
//!
//! See the README in `~/src/postgres/contrib/pg_plan_advice/` for
//! the design rationale and `~/src/postgres/src/include/nodes/pathnodes.h`
//! for the canonical bit assignments.

use serde::{Deserialize, Serialize};

/// Per-rel set of allowable plan strategies.
///
/// The mask is consulted by Ra's rule advisor and cost extractor;
/// when supplied advice clears bits, transformations that would
/// produce a forbidden strategy are demoted (rule advisor) or
/// penalised by [`Cost::DISABLE_PENALTY`][crate::feedback] in
/// extraction. A plan that requires a forbidden strategy still
/// extracts (with a high cost) — mirroring PG's
/// `Disabled: true` fallback behavior.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[repr(transparent)]
pub struct PgsMask(pub u64);

impl PgsMask {
    // -- Scan strategies -------------------------------------------
    pub const SEQ_SCAN:           u64 = 0x0000_0001;
    pub const INDEX_SCAN:         u64 = 0x0000_0002;
    pub const INDEX_ONLY_SCAN:    u64 = 0x0000_0004;
    pub const BITMAP_SCAN:        u64 = 0x0000_0008;
    pub const TID_SCAN:           u64 = 0x0000_0010;

    // -- Foreign / push-down --------------------------------------
    pub const FOREIGN_JOIN:       u64 = 0x0000_0020;

    // -- Join strategies ------------------------------------------
    pub const MERGE_JOIN_PLAIN:        u64 = 0x0000_0040;
    pub const MERGE_JOIN_MATERIALIZE:  u64 = 0x0000_0080;
    pub const NESTLOOP_PLAIN:          u64 = 0x0000_0100;
    pub const NESTLOOP_MATERIALIZE:    u64 = 0x0000_0200;
    pub const NESTLOOP_MEMOIZE:        u64 = 0x0000_0400;
    pub const HASH_JOIN:               u64 = 0x0000_0800;

    // -- Append / merge-append ------------------------------------
    pub const APPEND:                  u64 = 0x0000_1000;
    pub const MERGE_APPEND:            u64 = 0x0000_2000;

    // -- Parallel -------------------------------------------------
    pub const GATHER:                  u64 = 0x0000_4000;
    pub const GATHER_MERGE:            u64 = 0x0000_8000;

    // -- Consider* (planner-stage opt-ins) ------------------------
    pub const CONSIDER_INDEXONLY:        u64 = 0x0001_0000;
    pub const CONSIDER_PARTITIONWISE:    u64 = 0x0002_0000;
    pub const CONSIDER_NONPARTIAL:       u64 = 0x0004_0000;

    // -- Convenience compound masks (mirrored from pathnodes.h) ---
    pub const SCAN_ANY: u64 = Self::SEQ_SCAN
        | Self::INDEX_SCAN
        | Self::INDEX_ONLY_SCAN
        | Self::BITMAP_SCAN
        | Self::TID_SCAN;

    pub const MERGEJOIN_ANY: u64 =
        Self::MERGE_JOIN_PLAIN | Self::MERGE_JOIN_MATERIALIZE;

    pub const NESTLOOP_ANY: u64 = Self::NESTLOOP_PLAIN
        | Self::NESTLOOP_MATERIALIZE
        | Self::NESTLOOP_MEMOIZE;

    pub const JOIN_ANY: u64 = Self::FOREIGN_JOIN
        | Self::MERGEJOIN_ANY
        | Self::NESTLOOP_ANY
        | Self::HASH_JOIN;

    /// Initial value: every strategy is permitted.
    #[must_use]
    pub const fn all() -> Self {
        Self(
            Self::SCAN_ANY
                | Self::FOREIGN_JOIN
                | Self::MERGEJOIN_ANY
                | Self::NESTLOOP_ANY
                | Self::HASH_JOIN
                | Self::APPEND
                | Self::MERGE_APPEND
                | Self::GATHER
                | Self::GATHER_MERGE
                | Self::CONSIDER_INDEXONLY
                | Self::CONSIDER_PARTITIONWISE
                | Self::CONSIDER_NONPARTIAL,
        )
    }

    /// Test whether a single bit is set.
    #[must_use]
    pub const fn contains(self, bit: u64) -> bool {
        (self.0 & bit) != 0
    }

    /// Clear one or more bits; returns the new mask.
    #[must_use]
    pub const fn without(self, bits: u64) -> Self {
        Self(self.0 & !bits)
    }

    /// Set one or more bits; returns the new mask.
    #[must_use]
    pub const fn with(self, bits: u64) -> Self {
        Self(self.0 | bits)
    }
}

impl Default for PgsMask {
    fn default() -> Self {
        Self::all()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The bit values we use must match PG's `pathnodes.h`
    /// layout exactly. Encode the expected layout as a static
    /// table so any drift fails the test.
    #[test]
    fn bit_values_match_pg_pathnodes_h() {
        let pairs: &[(&str, u64)] = &[
            ("PGS_SEQSCAN", PgsMask::SEQ_SCAN),
            ("PGS_INDEXSCAN", PgsMask::INDEX_SCAN),
            ("PGS_INDEXONLYSCAN", PgsMask::INDEX_ONLY_SCAN),
            ("PGS_BITMAPSCAN", PgsMask::BITMAP_SCAN),
            ("PGS_TIDSCAN", PgsMask::TID_SCAN),
            ("PGS_FOREIGNJOIN", PgsMask::FOREIGN_JOIN),
            ("PGS_MERGEJOIN_PLAIN", PgsMask::MERGE_JOIN_PLAIN),
            ("PGS_MERGEJOIN_MATERIALIZE", PgsMask::MERGE_JOIN_MATERIALIZE),
            ("PGS_NESTLOOP_PLAIN", PgsMask::NESTLOOP_PLAIN),
            ("PGS_NESTLOOP_MATERIALIZE", PgsMask::NESTLOOP_MATERIALIZE),
            ("PGS_NESTLOOP_MEMOIZE", PgsMask::NESTLOOP_MEMOIZE),
            ("PGS_HASHJOIN", PgsMask::HASH_JOIN),
            ("PGS_APPEND", PgsMask::APPEND),
            ("PGS_MERGE_APPEND", PgsMask::MERGE_APPEND),
            ("PGS_GATHER", PgsMask::GATHER),
            ("PGS_GATHER_MERGE", PgsMask::GATHER_MERGE),
            ("PGS_CONSIDER_INDEXONLY", PgsMask::CONSIDER_INDEXONLY),
            ("PGS_CONSIDER_PARTITIONWISE", PgsMask::CONSIDER_PARTITIONWISE),
            ("PGS_CONSIDER_NONPARTIAL", PgsMask::CONSIDER_NONPARTIAL),
        ];
        // Each successive PGS_* bit is at the next bit position
        // (1, 2, 4, 8, ...), starting from bit 0. Validate that
        // by checking the values are each a power of two and
        // strictly increasing.
        for (i, (name, val)) in pairs.iter().enumerate() {
            let expected = 1u64 << i;
            assert_eq!(
                *val, expected,
                "{name} must be {expected:#x} (bit {i}) but is {val:#x}",
            );
        }
    }

    #[test]
    fn compound_masks_are_unions_of_components() {
        assert_eq!(
            PgsMask::SCAN_ANY,
            PgsMask::SEQ_SCAN
                | PgsMask::INDEX_SCAN
                | PgsMask::INDEX_ONLY_SCAN
                | PgsMask::BITMAP_SCAN
                | PgsMask::TID_SCAN,
        );
        assert_eq!(
            PgsMask::JOIN_ANY,
            PgsMask::FOREIGN_JOIN
                | PgsMask::MERGEJOIN_ANY
                | PgsMask::NESTLOOP_ANY
                | PgsMask::HASH_JOIN,
        );
    }

    #[test]
    fn default_is_all_permitted() {
        let m = PgsMask::default();
        assert!(m.contains(PgsMask::SEQ_SCAN));
        assert!(m.contains(PgsMask::HASH_JOIN));
        assert!(m.contains(PgsMask::CONSIDER_PARTITIONWISE));
    }

    #[test]
    fn without_clears_bits() {
        let m = PgsMask::default().without(PgsMask::SCAN_ANY);
        assert!(!m.contains(PgsMask::SEQ_SCAN));
        assert!(!m.contains(PgsMask::INDEX_SCAN));
        assert!(m.contains(PgsMask::HASH_JOIN));
    }
}
